# Generated by Django 4.2.10 on 2024-03-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_cryptoassets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoAssets',
        ),
    ]
