# Generated by Django 4.2.10 on 2024-03-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_opentrade_quantity_alter_opentrade_stop_loss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opentrade',
            old_name='price',
            new_name='entry',
        ),
    ]
