# Generated by Django 4.2.10 on 2024-03-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_transaction_street_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='type_of_transaction',
        ),
    ]
