# Generated by Django 4.2.10 on 2024-03-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type_of_transaction',
            new_name='transaction_type',
        ),
    ]
