# Generated by Django 4.2.10 on 2024-03-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_transaction_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
