# Generated by Django 4.2.10 on 2024-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deposit_amount_multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
