# Generated by Django 4.2.10 on 2024-03-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='charts',
        ),
        migrations.AddField(
            model_name='chart',
            name='number_of_charts',
            field=models.IntegerField(default=2),
        ),
    ]
