# Generated by Django 4.2.10 on 2024-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_remove_chart_charts_chart_number_of_charts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='number_of_charts',
        ),
        migrations.AddField(
            model_name='chart',
            name='crypto_charts',
            field=models.JSONField(blank=True, default=['BTCUSDT', 'ETHUSDT'], max_length=2, null=True),
        ),
    ]
