# Generated by Django 4.2.10 on 2024-03-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_remove_chart_number_of_charts_chart_crypto_charts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='crypto_charts',
            field=models.JSONField(blank=True, default=['BTCUSDT', 'ETHUSDT'], max_length=3, null=True),
        ),
    ]
